version: '3.9'

services:

  envoy:
    image: envoyproxy/envoy:v1.19-latest
    ports:
      - "9901:9901"
      - "10000:10000"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./Envoy/https.crt:/etc/ssl/certs/https.crt
      - ./Envoy/key.pem:/etc/ssl/certs/key.pem

  coffeeapi:
    image: ${DOCKER_REGISTRY:-}coffeeapi:${TAG:-latest}
    build: 
      context: .
      dockerfile: API/Coffee/Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/

  teaapi:
    image: ${DOCKER_REGISTRY:-}teaapi:${TAG:-latest}
    build: 
      context: .
      dockerfile: API/Tea/Dockerfile
    ports:
      - "8082:80"
      - "8083:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8083"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/

networks:
  apigatewaytest: